spring:
  profiles:
    include: productiondb

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update

  data:
    jpa:
      repositories:
        enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss



logging:
  level:
    com.handicraft.*: debug

