spring:
  profiles:
    include: developmentdb

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        show-sql: true
        database: mysql

  data:
    jpa:
      repositories:
        enable: true

  jackson:
    serialization:
      write-dates-as-timestamps:  false

logging:
  level:
    com.handicraft.*: debug