spring:
  profiles:
    include: development-core

  jackson:
    serialization:
      fail_on_empty_beans:  false

server:
  port: 9090


Authentication: MASTERHANDICRAFT

images-path: www.half-handicraft.com:9090/images/