spring:
  profiles:
    include: production-core

  jackson:
    serialization:
      fail_on_empty_beans:  false



server:
  port: 8080

Authentication: MASTERHANDICRAFT

images-path: www.half-handicraft.com:8080/images/
